from jqdata import *


"""
Bank Quant V5.4g - Highway dividend reviewed-operating frozen-signal JoinQuant script.

Purpose:
- Platform replication preparation for the frozen `highway_dividend_reviewed_operating_v54g` candidate.
- This is not an accepted strategy and must not be tuned after seeing JoinQuant results.

Frozen rule:
- Use the 17 rebalance signals generated by local V5.4g full-coverage engineering smoke test.
- Rebalance only on exact frozen signal dates.
- Equal weight selected stocks with target exposure 99.5%.
- If fewer than 8 names are selected in early reviewed-operating years, keep residual cash.
- No timing overlay, no stop loss, no take profit, no return tuning.
- Formal execution keeps the fixed max-8 allocation contract. If account capital is too small to buy one lot per target name, the script logs a capital warning instead of changing the research rule.

Known comparison contract:
- Local runner used daily open for trade price and daily close for valuation.
- JoinQuant scheduled execution is at 09:40, so small execution differences are expected.
- Local benchmark was internal same-pool highway equal-weight.
- JoinQuant display benchmark uses 000027.XSHG (180运输), a supported transport-related index.
- 000027.XSHG is not a pure highway index, so sector-relative judgment should still use the local same-pool highway equal-weight benchmark.
"""


FROZEN_SIGNALS = {
    '2022-04-01': ['600350.XSHG', '000429.XSHE', '600033.XSHG', '600012.XSHG'],
    '2022-07-01': ['600350.XSHG', '600033.XSHG', '000429.XSHE', '600012.XSHG', '600035.XSHG', '000755.XSHE'],
    '2022-10-10': ['000429.XSHE', '600033.XSHG', '600012.XSHG', '600350.XSHG', '600035.XSHG', '000755.XSHE'],
    '2023-01-03': ['000429.XSHE', '600012.XSHG', '600033.XSHG', '600350.XSHG', '600035.XSHG', '000755.XSHE'],
    '2023-04-03': ['000429.XSHE', '600033.XSHG', '600012.XSHG', '600350.XSHG', '600377.XSHG', '600035.XSHG', '000755.XSHE'],
    '2023-07-03': ['000429.XSHE', '600012.XSHG', '600350.XSHG', '600377.XSHG', '600035.XSHG', '000755.XSHE', '600020.XSHG', '600033.XSHG'],
    '2023-10-09': ['000429.XSHE', '600033.XSHG', '600012.XSHG', '600350.XSHG', '600377.XSHG', '600035.XSHG', '000755.XSHE', '600020.XSHG'],
    '2024-01-02': ['000429.XSHE', '600033.XSHG', '600012.XSHG', '600035.XSHG', '600350.XSHG', '600377.XSHG', '000755.XSHE', '000900.XSHE'],
    '2024-04-01': ['600033.XSHG', '000429.XSHE', '600377.XSHG', '600350.XSHG', '600035.XSHG', '600012.XSHG', '000900.XSHE', '000755.XSHE'],
    '2024-07-01': ['600033.XSHG', '000429.XSHE', '600035.XSHG', '600020.XSHG', '600377.XSHG', '600350.XSHG', '600012.XSHG', '000900.XSHE'],
    '2024-10-08': ['000429.XSHE', '600035.XSHG', '600350.XSHG', '000828.XSHE', '600033.XSHG', '600012.XSHG', '600020.XSHG', '000900.XSHE'],
    '2025-01-02': ['600033.XSHG', '000828.XSHE', '000429.XSHE', '600035.XSHG', '600350.XSHG', '600020.XSHG', '600012.XSHG', '000900.XSHE'],
    '2025-04-01': ['600033.XSHG', '000828.XSHE', '600035.XSHG', '000429.XSHE', '600350.XSHG', '600020.XSHG', '000900.XSHE', '600012.XSHG'],
    '2025-07-01': ['000755.XSHE', '000429.XSHE', '000828.XSHE', '600035.XSHG', '600012.XSHG', '600033.XSHG', '000900.XSHE', '600377.XSHG'],
    '2025-10-09': ['000429.XSHE', '000755.XSHE', '000828.XSHE', '600012.XSHG', '600350.XSHG', '600020.XSHG', '600033.XSHG', '600035.XSHG'],
    '2026-01-05': ['000429.XSHE', '000755.XSHE', '000828.XSHE', '600020.XSHG', '600012.XSHG', '600035.XSHG', '600350.XSHG', '600377.XSHG'],
    '2026-04-01': ['000828.XSHE', '000755.XSHE', '000429.XSHE', '600020.XSHG', '600012.XSHG', '600035.XSHG', '600033.XSHG', '600377.XSHG'],
}

FIRST_SIGNAL_DATE = min(FROZEN_SIGNALS.keys())


def initialize(context):
    set_benchmark('000027.XSHG')
    set_option('use_real_price', True)
    set_option('avoid_future_data', True)
    set_order_cost(
        OrderCost(open_commission=0.0003, close_commission=0.0003, min_commission=5),
        type='stock',
    )

    g.strategy_id = 'highway_dividend_reviewed_operating_v54g'
    g.script_version = 'v54g_highway_frozen_signals_20260718'
    g.target_exposure = 0.995
    g.selection_count = 8
    g.lot_size = 100
    g.compact_small_capital = False
    g.executed_dates = set()
    g.debug = True

    log.info(
        'V5.4g highway script=%s frozen_signal_dates=%d target_exposure=%.4f joinquant_display_benchmark=000027.XSHG'
        % (g.script_version, len(FROZEN_SIGNALS), g.target_exposure)
    )
    log.info('V5.4g first frozen signal date=%s; dates before this are intentional warm-up/no-signal cash period.' % FIRST_SIGNAL_DATE)
    log.info('V5.4g benchmark note: 000027.XSHG is 180 transport, not a pure highway benchmark; use local highway equal-weight for formal sector-relative attribution.')
    log.info('V5.4g frozen rule: high-dividend highway selected stocks from local reviewed-operating PIT panel; no tuning.')

    run_daily(maybe_rebalance, time='09:40')
    run_daily(after_close_log, time='after_close')


def maybe_rebalance(context):
    today = context.current_dt.date().isoformat()
    if today not in FROZEN_SIGNALS:
        return
    if today in g.executed_dates:
        return

    selected = [code for code in FROZEN_SIGNALS[today] if is_tradable(code)]
    if not selected:
        log.info('V5.4g BLOCKED no tradable selected stocks date=%s' % today)
        g.executed_dates.add(today)
        return

    allocation_count = g.selection_count
    if g.compact_small_capital:
        allocation_count = min(g.selection_count, len(selected))
    target_weight = g.target_exposure / float(allocation_count)
    target_value = context.portfolio.total_value * target_weight
    log.info(
        'V5.4g rebalance date=%s raw_selected=%d tradable_selected=%d allocation_count=%d target_weight=%.6f target_value=%.2f selected=%s'
        % (today, len(FROZEN_SIGNALS[today]), len(selected), allocation_count, target_weight, target_value, ','.join(selected))
    )

    execute_target_values(context, selected, target_value)
    g.executed_dates.add(today)


def execute_target_values(context, selected, target_value):
    selected_set = set(selected)
    current_positions = list(context.portfolio.positions.keys())
    current_data = get_current_data()

    for code in current_positions:
        if code not in selected_set:
            try:
                order_target_value(code, 0)
            except Exception as exc:
                log.info('V5.4g sell failed code=%s error=%s' % (code, str(exc)))

    for code in selected:
        estimated_price = get_estimated_trade_price(current_data, code)
        if estimated_price is not None:
            min_lot_value = estimated_price * g.lot_size
            if target_value < min_lot_value:
                log.info(
                    'V5.4g capital warning code=%s target_value=%.2f one_lot_value=%.2f price=%.3f lot_size=%d; order may be rejected by lot-size rule.'
                    % (code, target_value, min_lot_value, estimated_price, g.lot_size)
                )
        try:
            order_target_value(code, target_value)
        except Exception as exc:
            log.info('V5.4g buy/adjust failed code=%s target_value=%.2f error=%s' % (code, target_value, str(exc)))


def get_estimated_trade_price(current_data, code):
    try:
        item = current_data[code]
    except Exception:
        return None
    for attr in ('last_price', 'day_open', 'high_limit', 'low_limit'):
        try:
            value = getattr(item, attr, None)
        except Exception:
            value = None
        if value is not None and value > 0:
            return float(value)
    return None


def is_tradable(code):
    current_data = get_current_data()
    try:
        item = current_data[code]
    except Exception:
        return False
    if getattr(item, 'paused', False):
        return False
    if getattr(item, 'is_st', False):
        return False
    return True


def after_close_log(context):
    today = context.current_dt.date().isoformat()
    if today not in FROZEN_SIGNALS:
        return
    positions = []
    for code, pos in context.portfolio.positions.items():
        if pos.total_amount > 0:
            positions.append('%s:%s' % (code, int(pos.total_amount)))
    log.info(
        'V5.4g after_close date=%s total_value=%.2f cash=%.2f positions=%s'
        % (today, context.portfolio.total_value, context.portfolio.cash, ';'.join(positions))
    )
