from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from v5.dividend_low_vol_fcf_screener_runner import (
    DEFAULT_CONFIG as DEFAULT_SCREEN_CONFIG,
    DEFAULT_STATUS_REGISTRY,
    run_dividend_low_vol_fcf_batch_screening,
)
from v5.io_utils import read_csv_rows, write_json_file
from v5.sector_replication_roadmap_runner import (
    DEFAULT_CONFIG as DEFAULT_ROADMAP_CONFIG,
    build_sector_replication_roadmap,
)


DEFAULT_OUT_DIR = Path("sector_replication_batches_v59")


@dataclass(frozen=True)
class SectorReplicationBatchResult:
    output_dir: Path
    screening_summary_path: Path
    roadmap_summary_path: Path
    packet_path: Path
    report_path: Path
    sector_count: int
    lane_counts: dict[str, int]


def run_sector_replication_batch(
    screen_config: Path = DEFAULT_SCREEN_CONFIG,
    roadmap_config: Path = DEFAULT_ROADMAP_CONFIG,
    status_registry: Path = DEFAULT_STATUS_REGISTRY,
    out_dir: Path = DEFAULT_OUT_DIR,
) -> SectorReplicationBatchResult:
    screening_out = out_dir / "screening"
    roadmap_out = out_dir / "roadmap"
    screening = run_dividend_low_vol_fcf_batch_screening(screen_config, status_registry, screening_out)

    effective_roadmap_config = _write_effective_roadmap_config(
        roadmap_config,
        out_dir / "effective_sector_replication_roadmap_config.json",
        screening.csv_path,
        screening.json_path,
    )
    roadmap = build_sector_replication_roadmap(effective_roadmap_config, roadmap_out)
    roadmap_rows = read_csv_rows(roadmap.csv_path)
    packet = _build_packet(screen_config, roadmap_config, status_registry, screening, roadmap, roadmap_rows)

    packet_path = out_dir / "sector_replication_batch_packet.json"
    report_path = out_dir / "sector_replication_batch_pm_report.md"
    write_json_file(packet_path, packet)
    report_path.write_text(_build_report(packet, roadmap_rows), encoding="utf-8")

    return SectorReplicationBatchResult(
        output_dir=out_dir,
        screening_summary_path=screening.json_path,
        roadmap_summary_path=roadmap.json_path,
        packet_path=packet_path,
        report_path=report_path,
        sector_count=roadmap.sector_count,
        lane_counts=roadmap.lane_counts,
    )


def _write_effective_roadmap_config(
    source_path: Path,
    output_path: Path,
    screening_results: Path,
    screening_summary: Path,
) -> Path:
    config = _read_json(source_path)
    config["source_screening_results"] = str(screening_results)
    config["source_screening_summary"] = str(screening_summary)
    config["batch_controller_note"] = (
        "Generated by sector_replication_batch_runner so roadmap consumes the same screening output from this run."
    )
    write_json_file(output_path, config)
    return output_path


def _build_packet(
    screen_config: Path,
    roadmap_config: Path,
    status_registry: Path,
    screening: Any,
    roadmap: Any,
    roadmap_rows: list[dict[str, str]],
) -> dict[str, Any]:
    lane_counts = dict(roadmap.lane_counts)
    return {
        "schema_version": 1,
        "strategy_family": "dividend_low_volatility_operating_cash_flow_enhanced_etf",
        "experiment_layer": "pm_decision_gate",
        "status": "batch_sector_replication_routed_not_model_acceptance",
        "created_at_utc": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "inputs": {
            "screen_config": str(screen_config),
            "roadmap_config": str(roadmap_config),
            "status_registry": str(status_registry),
        },
        "outputs": {
            "screening_summary": str(screening.json_path),
            "screening_results": str(screening.csv_path),
            "screening_report": str(screening.report_path),
            "roadmap_summary": str(roadmap.json_path),
            "roadmap_csv": str(roadmap.csv_path),
            "roadmap_report": str(roadmap.report_path),
            "agent_queue_dir": str(roadmap.queue_dir),
        },
        "sector_count": roadmap.sector_count,
        "lane_counts": lane_counts,
        "next_execution_order": _execution_order(roadmap_rows),
        "pm_rules": [
            "Batch traversal is allowed; strategy acceptance is not.",
            "Research Agent must pass industry knowledge and data availability gates before Quant validation.",
            "Quant Validation Agent must run baseline, IC/RankIC, rolling, ablation and robustness before Engineering handoff.",
            "Engineering Agent only handles frozen candidates and must output local daily simulation, dividends, trades, cash, holdings and rebalance_order_health.",
            "No sector may be promoted because historical return looks good.",
            "Two consecutive loops without new evidence produce a blocker or failure-return packet.",
        ],
    }


def _execution_order(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    result = []
    for row in rows:
        result.append(
            {
                "priority_rank": row.get("priority_rank", ""),
                "sector_id": row.get("sector_id", ""),
                "display_name": row.get("display_name", ""),
                "pm_lane": row.get("pm_lane", ""),
                "next_agent": row.get("next_agent", ""),
                "timebox_minutes": row.get("timebox_minutes", ""),
                "required_packet": row.get("required_packet", ""),
                "allowed_next_action": row.get("allowed_next_action", ""),
                "graduation_gate": row.get("graduation_gate", ""),
                "stop_condition": row.get("stop_condition", ""),
            }
        )
    return result


def _build_report(packet: dict[str, Any], roadmap_rows: list[dict[str, str]]) -> str:
    lines = [
        "# V5 Sector Replication Batch PM Report",
        "",
        f"Created at UTC: `{packet['created_at_utc']}`",
        "",
        "## Decision",
        "",
        "The nearby-sector replication process is now routed as one batch. This is a PM routing packet, not model acceptance.",
        "",
        "## Lane Counts",
        "",
        "| Lane | Count |",
        "| --- | ---: |",
    ]
    for lane, count in sorted(packet["lane_counts"].items()):
        lines.append(f"| `{lane}` | {count} |")
    lines.extend(
        [
            "",
            "## Execution Queue",
            "",
            "| Rank | Sector | Lane | Agent | Timebox | Next action | Stop condition |",
            "| ---: | --- | --- | --- | ---: | --- | --- |",
        ]
    )
    for row in roadmap_rows:
        lines.append(
            "| {rank} | {sector} | `{lane}` | {agent} | {minutes} | {action} | {stop} |".format(
                rank=row.get("priority_rank", ""),
                sector=row.get("display_name") or row.get("sector_id", ""),
                lane=row.get("pm_lane", ""),
                agent=row.get("next_agent", ""),
                minutes=row.get("timebox_minutes", ""),
                action=row.get("allowed_next_action", ""),
                stop=row.get("stop_condition", ""),
            )
        )
    lines.extend(
        [
            "",
            "## Hard Rules",
            "",
        ]
    )
    for rule in packet["pm_rules"]:
        lines.append(f"- {rule}")
    lines.extend(
        [
            "",
            "## Output Paths",
            "",
            f"- Screening summary: `{packet['outputs']['screening_summary']}`",
            f"- Roadmap summary: `{packet['outputs']['roadmap_summary']}`",
            f"- Agent queue dir: `{packet['outputs']['agent_queue_dir']}`",
            "",
        ]
    )
    return "\n".join(lines)


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8-sig") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload
